server:
  port: 8083
  servlet:
    context-path: /sell

spring:
  application:
    name: sell
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root


  jackson:
    default-property-inclusion: non_null

mybatis:
    type-aliases-package: com.amy.sell.model
    mapper-locations: classpath:mapper/*.xml
    #驼峰命名法
    configuration:
      map-underscore-to-camel-case: true



#日志
logback:
  logdir: D:\log\sell